# Generated by Django 5.1.2 on 2024-10-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0002_logintable_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
