# Generated by Django 5.1.2 on 2024-10-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0010_patientprofile_age_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time_from', models.TimeField()),
                ('appointment_time_to', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_hospitalityapp.doctorprofile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='e_hospitalityapp.doctorprofile')),
            ],
        ),
    ]
