# Generated by Django 5.1.2 on 2024-10-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0016_alter_payment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_hospitalityapp.patientprofile'),
        ),
    ]
