# Generated by Django 5.1.2 on 2024-10-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0017_alter_medicalhistory_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='e_hospitalityapp.patientappointment'),
        ),
    ]
