# Generated by Django 5.1.2 on 2024-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0018_alter_payment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
