# Generated by Django 5.1.2 on 2024-10-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0019_patientprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
