# Generated by Django 5.1.2 on 2024-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0020_administrator_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
