# Generated by Django 5.1.2 on 2024-10-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0021_remove_patientprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='appointment_time_from',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='appointment_time_to',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='appoinment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_hospitalityapp.appointment'),
            preserve_default=False,
        ),
    ]
