# Generated by Django 5.1.2 on 2024-10-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitalityapp', '0023_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
